services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - POSTGRES_DB=ferremas_db
      - POSTGRES_USER=ferremas_user
      - POSTGRES_PASSWORD=ferremas_pass
      - DB_HOST=db
      - DB_PORT=5432

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: ferremas_db
      POSTGRES_USER: ferremas_user
      POSTGRES_PASSWORD: ferremas_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: